fix: use optionType instead of type for StrategyLeg (#17)
- Changed position.legs[0].type to position.legs[0].optionType
- Matches StrategyLeg interface definition

Fixes error: Property 'type' does not exist on type 'StrategyLeg'